### ISSUE TITLE
Request: Confirmation to Adjust lifetime of clones

### ISSUE THREAD

**Issue by UiharuKazari2008** [Er1807/FreezeFrame#1]
It would be nice to have a option to extend the the lifetime of clones avatars so I don’t have to feel like I’m in a rush if I setting of a scene for a photo or video

**Comment by Er1807** [comment]
Already fixed in https://github.com/Er1807/FreezeFrame/commit/297db88845dfb8b22b3bdb1974e2bd8d9e55da52 

Just waiti g for approval in VRCMG
